apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: site-ecommerce-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      name: site-ecommerce-pv